//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int ID { get; set; }
        public string NameDisCount { get; set; }
        public Nullable<decimal> PriceDicount { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> IDProduct { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
